/* eslint-disable linebreak-style */
export default {
  REQUESTING_DATA: 'REQUESTING_DATA',
  SET_POP_MOVIES: 'SET_POP_MOVIES',
  RECEIVED_MOVIE: 'RECEIVED_MOVIE',
  RECEIVED_SEARCH_RESULT: 'RECEIVED_SEARCH_RESULT',
  ERASE_MOVIE: 'ERASE_MOVIE',
  ERASE_SEARCH_RESULT: 'ERASE_SEARCH_RESULT',
  RECEIVED_ERROR: 'RECEIVED_ERROR',
};
