/* eslint-disable linebreak-style */
export default {
  REQUESTING_DATA: 'REQUESTING_DATA',
  SET_POP_MOVIES: 'SET_POP_MOVIES',
  SET_SELECTED_MOVIE: 'SET_SELECTED_MOVIE',
  SET_SEARCH_RESULT: 'SET_SEARCH_RESULT',
  ERASE_MOVIE: 'ERASE_MOVIE',
  ERASE_SEARCH_RESULT: 'ERASE_SEARCH_RESULT',
  RECEIVED_ERROR: 'RECEIVED_ERROR',
};
